#!/bin/sh
gpg --ignore-time-conflict --no-options --no-default-keyring \
	--secret-keyring /tmp/`basename $0`.$$.tmp --trustdb-name /etc/apt/trustdb.gpg \
	--keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg \
	--keyserver hkp://keyserver.ubuntu.com:80/ --recv $*
